// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoW0KekFizrtKSyep-zSNRMHe9aesZh-8',
    appId: '1:604155204030:web:2611608cd1b554671069ef',
    messagingSenderId: '604155204030',
    projectId: 'chat-app-456ca',
    authDomain: 'chat-app-456ca.firebaseapp.com',
    storageBucket: 'chat-app-456ca.appspot.com',
    measurementId: 'G-YYQTXF9RGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL49xKBqF-4iL_V9ECLZy_lGz_V_glzTQ',
    appId: '1:604155204030:android:9907fd070822eccc1069ef',
    messagingSenderId: '604155204030',
    projectId: 'chat-app-456ca',
    storageBucket: 'chat-app-456ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbg6w89CWN7t8vwjPcBGHShOHaPAW6UJ4',
    appId: '1:604155204030:ios:683f3aacafcfa3e51069ef',
    messagingSenderId: '604155204030',
    projectId: 'chat-app-456ca',
    storageBucket: 'chat-app-456ca.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbg6w89CWN7t8vwjPcBGHShOHaPAW6UJ4',
    appId: '1:604155204030:ios:683f3aacafcfa3e51069ef',
    messagingSenderId: '604155204030',
    projectId: 'chat-app-456ca',
    storageBucket: 'chat-app-456ca.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoW0KekFizrtKSyep-zSNRMHe9aesZh-8',
    appId: '1:604155204030:web:16b5ce902a4683941069ef',
    messagingSenderId: '604155204030',
    projectId: 'chat-app-456ca',
    authDomain: 'chat-app-456ca.firebaseapp.com',
    storageBucket: 'chat-app-456ca.appspot.com',
    measurementId: 'G-GETHP5L0F8',
  );
}
